# -*- coding: utf-8 -*-
"""python_basics_nithin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gRxJ4Gt7roPWGRqIN6qsI2KuAoeHCsG
"""

# Task 1: Variables and Data Types
name = "Arjun"
age = 21
height = 1.75
is_student = True

# Printing all four values in a single statement
print(name, age, height, is_student)

# Task 2: String Formatting
# Using an f-string for clean formatting
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

# Task 3: Arithmetic Operations
age_months = age * 12
age_days = age * 365
remainder_by_seven = age % 7
age_squared = age ** 2

print("Age in months:", age_months)
print("Age in days:", age_days)
print("Remainder when divided by 7:", remainder_by_seven)
print("Age squared:", age_squared)